baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"
hasCJKLanguage = true
title = "Esther's Life"
theme = "zozo"
summaryLength = 0
paginate = 5
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]
  name = "Esther"

[blackfriday]
  smartypants = false

[[menu.main]]
  name = "Esther"
  weight = 1
  identifier = "about"
  url = "/esther/"
[[menu.main]]
  name = "Portfolio"
  weight = 2
  identifier = "portfolio"
  url = "/portfolio/"
[[menu.main]]
  name = "Archives"
  weight = 3
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Playground"
  weight = 4
  identifier = "playground"
  url = "/playground/"

[params]
  subTitle = "As a front end newbie..."
  footerSlogan = "Life would be tragic if it weren't funny. 🍿"
  keywords = [""]
  description = "Esther's frontend newbie life"
  enableMathJax = false
  enableSummary = true
  mainSections = ["posts","post"]

[social]
  github = "https://github.com/estherj-hsu"
  twitter = ""
  facebook = ""
  weibo = ""
  instagram = ""

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true